version: 2.1

jobs:
  build:
    docker:
      - image: hugomods/hugo:latest
    steps:
      - checkout

      - run:
          name: Setup Git Configuration
          command: |
            git config --global push.default matching
            git config --global user.email "abhi.pandey@gmail.com"
            git config --global user.name "abhi1010"
            sudo apt-get update
            sudo apt-get install -y openssh-client

      - run:
          name: Prepare Repository
          command: |
            pwd
            ls
            ./prepare.sh

      - run:
          name: Build Hugo Site
          command: |
            pwd
            ls
            ./build.sh

      - run:
          name: Deploy to GitHub Pages
          command: |
            echo `pwd`
            export NOW_HOUR=$(date +%d-%b-%H_%M)
            pwd && ls
            git config --get remote.origin.url
            git remote set-url origin git@github.com:abhi1010/abhi1010.github.io.git
            cd abhi1010.github.io
            pwd
            git status -s
            echo -e "a\n*\nq\n"|git add -i
            git commit -vam "Automated build from CircleCI - $NOW_HOUR"
            git remote show origin
            git push -v

      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - .

notify:
  webhooks:
    - url: https://example.com/hooks/circle

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master